// src/component/VizPanel.tsx
import React from 'react'
import WaveViz from './WaveViz'
import BarsViz from './BarsViz'
import WaterfallViz from './WaterfallViz'
import fullScreenBlack from '../assets/fullScreenBlack.png'
import fullScreenWhite from '../assets/fullScreenWhite.png'
import { t, tn } from '../i18n'
import { AudioViz } from '../types'

type VizPanelProps = {
  theme: any
  hideRms: boolean
  viz: AudioViz | null
  mode: 'wave'|'bars'|'waterfall'
  onToggle: () => void
  themeName: 'dark'|'light'
}

export default function VizPanel({ theme, hideRms, viz, mode, onToggle, themeName }: VizPanelProps) {
  // 自适应高度：在默认窗口高度（≈390）时保持 120px，随着窗口拉高按比例增大，设上下限
  const baseWindowH = 390
  const baseVizH = 120
  const vh = typeof window !== 'undefined' ? window.innerHeight : baseWindowH
  const h = Math.max(100, Math.min(300, Math.floor(baseVizH + Math.max(0, vh - baseWindowH) * 0.7)))
  const w = Math.max(180, Math.floor(window.innerWidth))
  const bg = theme.panelBg
  const grid = theme.grid
  const line = theme.line
  const accent = theme.accent
  const rmsRaw = viz?.rms ?? 0
  const samples = viz?.samples ?? []
  const silentCut = 0.015
  // 快速静音判定：当音量相对上一帧骤降，直接视为静音（解决“戛然而止”不归零）
  const prevRmsRef = React.useRef(0)
  const [fastSilent, setFastSilent] = React.useState(false)
  React.useEffect(() => {
    const prev = prevRmsRef.current
    const drop = prev > 0.08 && rmsRaw < prev * 0.25
    setFastSilent(drop)
    prevRmsRef.current = rmsRaw
  }, [rmsRaw])
  const isSilent = rmsRaw < silentCut || fastSilent

  // 帧间平滑：用 ref 避免 setState 导致的渲染环
  const lastSmoothedRef = React.useRef<number[] | null>(null)
  const smoothSamples = React.useMemo(() => {
    const alpha = 0.35
    const base = isSilent ? new Array(samples.length).fill(0) : samples
    if (!base.length) return [] as number[]
    const prev = lastSmoothedRef.current
    if (!prev || prev.length !== base.length) {
      lastSmoothedRef.current = base
      return base
    }
    const out = new Array(base.length)
    for (let i = 0; i < base.length; i++) {
      out[i] = prev[i] * (1 - alpha) + base[i] * alpha
    }
    lastSmoothedRef.current = out
    return out
  }, [samples, isSilent])

  // RMS 平滑（用 ref，避免触发重渲染环）
  const rmsSmoothedRef = React.useRef(0)
  React.useEffect(() => {
    const prev = rmsSmoothedRef.current
    if (isSilent) { rmsSmoothedRef.current = 0; return }
    const alphaUp = 0.15
    const alphaDown = 0.35
    const alpha = rmsRaw < prev ? alphaDown : alphaUp
    rmsSmoothedRef.current = prev * (1 - alpha) + rmsRaw * alpha
  }, [rmsRaw, isSilent])

  // 自适应增益（用 ref）
  const peakRef = React.useRef(0.3)
  React.useEffect(() => {
    if (!smoothSamples.length) return
    let localPeak = 0
    for (let i = 0; i < smoothSamples.length; i++) {
      const a = Math.abs(smoothSamples[i] || 0)
      if (a > localPeak) localPeak = a
    }
    peakRef.current = isSilent ? 0.2 : (peakRef.current * 0.95 + localPeak * 0.05)
  }, [smoothSamples, isSilent])
  // 降低基础增益，并限制上下限，取折中视觉效果
  const base = Math.max(0.12, Math.min(0.6, peakRef.current))
  let gain = 0.6 / base
  gain = Math.max(0.8, Math.min(2.2, gain))

  // Waterfall 历史与参数占位（自适应将在计算有效高度后进行）
  const histRef = React.useRef<number[][]>([])
  function heatColor(v: number) {
    // 强化对比度但保持原色系：
    // 低 -> #24060d, 中(≈#eb1a50) -> 高 -> #ffd6e1
    const clamp = (x: number) => Math.max(0, Math.min(1, x))
    const enhance = (x: number, c = 1.45, pivot = 0.55) => clamp((x - pivot) * c + pivot)
    const t = enhance(clamp(v))
    const mid = 0.6
    const lerp = (a: number, b: number, t: number) => Math.round(a + (b - a) * t)
    if (t <= mid) {
      const u = t / mid
      const r = lerp(36, 235, u) // 24 -> eb
      const g = lerp(6, 26, u)   // 06 -> 1a
      const b = lerp(13, 80, u)  // 0d -> 50
      return `rgb(${r},${g},${b})`
    } else {
      const u = (t - mid) / (1 - mid)
      const r = lerp(235, 255, u)
      const g = lerp(26, 214, u)
      const b = lerp(80, 225, u)
      return `rgb(${r},${g},${b})`
    }
  }
  // barLen 延后基于 svgW 计算
  // 全屏图标显隐与全屏控制
  const containerRef = React.useRef<HTMLDivElement | null>(null)
  const [hovered, setHovered] = React.useState(false)
  const [isFullscreen, setIsFullscreen] = React.useState(false)
  React.useEffect(() => {
    function onFsChange() {
      setIsFullscreen(!!document.fullscreenElement)
    }
    document.addEventListener('fullscreenchange', onFsChange)
    return () => document.removeEventListener('fullscreenchange', onFsChange)
  }, [])
  async function enterFullscreen(e?: React.MouseEvent) {
    if (e) { e.stopPropagation(); e.preventDefault() }
    const el = containerRef.current
    if (!el) return
    try {
      if (el.requestFullscreen) await el.requestFullscreen()
    } catch {}
  }
  const fsIcon = themeName === 'dark' ? fullScreenWhite : fullScreenBlack

  // 基于全屏状态决定可视化高度
  const fullH = typeof window !== 'undefined'
    ? Math.max(window.innerHeight || 0, (window.screen && (window.screen as any).height) || 0, document.documentElement?.clientHeight || 0)
    : baseWindowH
  const effectiveH = isFullscreen
    ? Math.max(100, Math.floor(fullH - (hideRms ? 20 : 36)))
    : h
  // 依据有效高度自适应 Waterfall 的 bands 与 cell，并重新计算垂直偏移
  const gap = 1
  const baseH = baseVizH
  const baseBands = 16
  // 高度越大频带越多：从 16 线性增加到 24（最长到 32），避免过密
  const scaleH = Math.max(0, Math.min(1, (effectiveH - 120) / 360))
  const bands = Math.max(8, Math.min(32, Math.round(baseBands + scaleH * 8)))
  const baseCell = 4
  const baseContentH = Math.min(baseH, bands * (baseCell + gap) + gap)
  const idealPaddingY = Math.max(0, Math.floor((baseH - baseContentH) / 2))
  const targetContentH2 = Math.max(10, effectiveH - idealPaddingY * 2)
  const cell2 = Math.max(2, Math.min(16, Math.floor((targetContentH2 - gap) / bands - gap)))
  const wfH2 = Math.min(effectiveH, bands * (cell2 + gap) + gap)
  const extraY2 = Math.max(0, Math.floor((effectiveH - 2 * idealPaddingY - wfH2) / 2))
  const wfOffsetYEffective = Math.max(0, idealPaddingY + extraY2)

  // 将一帧样本折叠为自适应 bands 段能量
  const frameBands = React.useMemo(() => {
    const out = new Array(bands).fill(0)
    if (!smoothSamples.length) return out
    const step = Math.max(1, Math.floor(smoothSamples.length / bands))
    for (let b = 0; b < bands; b++) {
      const i0 = b * step
      const i1 = Math.min(smoothSamples.length, i0 + step)
      let acc = 0, cnt = 0
      for (let i = i0; i < i1; i++) { acc += Math.abs(smoothSamples[i] || 0); cnt++ }
      const v = cnt ? acc / cnt : 0
      out[b] = Math.min(1, v * gain)
    }
    return out
  }, [smoothSamples, gain, bands])

  // 维护历史（右侧为最新），按固定滚动倍速推进；当 bands 变化时不回溯转换历史，仅按新 bands 写入
  const scrollMul = 6
  const maxHistory = 600
  React.useEffect(() => {
    if (!frameBands.length) return
    let next = histRef.current.slice()
    for (let i = 0; i < scrollMul; i++) next.push(frameBands)
    if (next.length > maxHistory) next = next.slice(next.length - maxHistory)
    histRef.current = next
  }, [frameBands])
  const visibleCols2 = Math.max(1, Math.floor((w - gap) / (cell2 + gap)))

  // 按宽度自适应柱状图根数：目标单元宽度（含1px间隙）约 5px，限制区间 [32, 256]
  const targetCellPx = 5
  const barsCount = Math.max(32, Math.min(256, Math.floor(w / targetCellPx)))

  return (
    <div
      ref={containerRef}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{width:w, display:'flex', flexDirection:'column', gap:6, padding:0}}
    >
      <div style={{position:'relative'}}>
        {(() => {
          const paddingX = isFullscreen ? 0 : 5
          const svgW = Math.max(10, w - paddingX * 2)
          return (
            <svg width={svgW} height={effectiveH} style={{background:bg, border:'1px solid #1d2a3a', borderRadius:6, cursor:'pointer', display:'block', margin:'0 auto'}} onClick={onToggle}>
              {mode === 'wave' && (
                <WaveViz width={svgW} height={effectiveH} samples={smoothSamples} gain={gain} gridColor={grid} lineColor={line} />
              )}
              {mode === 'bars' && (() => {
                const barGap = 1
                const minBarW = 2
                const barsWanted = Math.max(32, Math.min(2048, Math.floor((svgW + barGap) / (minBarW + barGap))))
                return <BarsViz width={svgW} height={effectiveH} samples={smoothSamples} gain={gain} barColor={line} bars={barsWanted} />
              })()}
              {mode === 'waterfall' && (
                <WaterfallViz width={svgW} height={effectiveH} bands={bands} gap={gap} cell={cell2} cellX={Math.max(2, Math.min(8, Math.round(cell2)))} history={histRef.current} heatColor={heatColor} overrideOffsetY={wfOffsetYEffective} />
              )}
            </svg>
          )
        })()}
        {/* 悬浮全屏图标 */}
        {!isFullscreen && (
          <button
            onClick={enterFullscreen}
            title={tn('全屏','Fullscreen')}
            style={{
              position:'absolute',
              right:8,
              top:8,
              width:26,
              height:26,
              padding:0,
              margin:0,
              border:'none',
              background:'transparent',
              cursor:'pointer',
              opacity: hovered ? 1 : 0,
              transform: hovered ? 'translateY(0) scale(1)' : 'translateY(-4px) scale(0.96)',
              transition:'opacity 160ms ease, transform 160ms ease'
            }}
          >
            <img src={fsIcon} alt={tn('全屏','Fullscreen')} width={26} height={26} draggable={false} />
          </button>
        )}
      </div>
      {!hideRms && (
        (() => {
          const paddingX = isFullscreen ? 0 : 5
          const svgW = Math.max(10, w - paddingX * 2)
          const trackW = Math.max(60, svgW - 60)
          const fillW = Math.max(0, Math.min(trackW, Math.round(rmsSmoothedRef.current * trackW)))
          return (
            <div title={t('rms_tooltip')} style={{display:'flex', alignItems:'center', gap:8, height:14, width:svgW, margin:'0 auto'}}>
              <div style={{width:trackW, height:8, background:'#3a0b17', borderRadius:4, overflow:'hidden'}}>
                <div style={{width:fillW, height:'100%', background:accent, transition:'width 120ms'}} />
              </div>
              <span style={{fontSize:12, lineHeight:'14px', color:'#6b829e'}}>
                RMS {Math.round(rmsSmoothedRef.current*100)}%
              </span>
            </div>
          )
        })()
      )}
    </div>
  )
}

// website/src/components/bpm/VizPanel.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import WaveViz from './WaveViz.vue'
import BarsViz from './BarsViz.vue'
import WaterfallViz from './WaterfallViz.vue'
import fullscreenLight from '../../assets/bpm/fullScreenWhite.png'
import fullscreenDark from '../../assets/bpm/fullScreenBlack.png'

type VizMode = 'wave' | 'bars' | 'waterfall'

type AudioViz = { samples: number[]; rms: number }

const props = withDefaults(
  defineProps<{
    theme: Record<string, string>
    hideRms?: boolean
    viz?: AudioViz | null
    mode?: VizMode
    themeName?: 'dark' | 'light'
    width?: number
    baseHeight?: number
  }>(),
  {
    hideRms: false,
    viz: () => ({ samples: [], rms: 0 }),
    mode: 'wave',
    themeName: 'dark',
    width: 360,
    baseHeight: 140
  }
)

const emit = defineEmits<{ toggle: [] }>()

const containerRef = ref<HTMLElement | null>(null)
const hovered = ref(false)
const isFullscreen = ref(false)

function onFsChange() {
  isFullscreen.value = !!document.fullscreenElement
}

async function enterFullscreen(e?: MouseEvent) {
  e?.stopPropagation()
  e?.preventDefault()
  const el = containerRef.value
  if (!el) return
  try {
    if (el.requestFullscreen) await el.requestFullscreen()
  } catch {
    // ignore
  }
}

onMounted(() => {
  document.addEventListener('fullscreenchange', onFsChange)
})

onUnmounted(() => {
  document.removeEventListener('fullscreenchange', onFsChange)
})

const effectiveWidth = computed(() => {
  if (isFullscreen.value && typeof window !== 'undefined') {
    return Math.max(window.innerWidth || document.documentElement?.clientWidth || 600, 360)
  }
  return props.width
})

const effectiveHeight = computed(() => {
  if (isFullscreen.value && typeof window !== 'undefined') {
    const fullH = Math.max(
      window.innerHeight || 0,
      (window.screen && (window.screen as any).height) || 0,
      document.documentElement?.clientHeight || 0
    )
    return Math.max(140, fullH - (props.hideRms ? 20 : 50))
  }
  return props.baseHeight
})

const smoothSamples = ref<number[]>([])
const prevSamples = ref<number[]>([])
const silentCut = 0.015
const prevRms = ref(0)
const fastSilent = ref(false)
const isSilent = ref(false)

watch(
  () => props.viz?.rms ?? 0,
  (rms) => {
    const drop = prevRms.value > 0.08 && rms < prevRms.value * 0.25
    fastSilent.value = drop
    prevRms.value = rms
    isSilent.value = rms < silentCut || drop
  },
  { immediate: true }
)

watch(
  () => props.viz?.samples,
  (samples = []) => {
    const base = isSilent.value ? new Array(samples.length).fill(0) : samples
    if (!base.length) {
      smoothSamples.value = []
      prevSamples.value = []
      return
    }
    if (!prevSamples.value.length || prevSamples.value.length !== base.length) {
      smoothSamples.value = [...base]
      prevSamples.value = [...base]
      return
    }
    const alpha = 0.35
    const out = new Array(base.length)
    for (let i = 0; i < base.length; i++) {
      out[i] = prevSamples.value[i] * (1 - alpha) + base[i] * alpha
    }
    smoothSamples.value = out
    prevSamples.value = out
  },
  { immediate: true }
)

const rmsSmoothed = ref(0)
watch(
  () => props.viz?.rms ?? 0,
  (rms) => {
    if (isSilent.value) {
      rmsSmoothed.value = 0
      return
    }
    const alphaUp = 0.15
    const alphaDown = 0.35
    const alpha = rms < rmsSmoothed.value ? alphaDown : alphaUp
    rmsSmoothed.value = rmsSmoothed.value * (1 - alpha) + rms * alpha
  },
  { immediate: true }
)

const peak = ref(0.3)
watch(
  () => smoothSamples.value,
  (samples) => {
    if (!samples.length) {
      peak.value = 0.2
      return
    }
    let localPeak = 0
    for (let i = 0; i < samples.length; i++) {
      const a = Math.abs(samples[i] || 0)
      if (a > localPeak) localPeak = a
    }
    peak.value = isSilent.value ? 0.2 : peak.value * 0.95 + localPeak * 0.05
  },
  { immediate: true }
)

const gain = computed(() => {
  const base = Math.max(0.12, Math.min(0.6, peak.value || 0.2))
  let g = 0.6 / base
  return Math.max(0.8, Math.min(2.2, g))
})

const gap = 1
const baseBands = 16
const maxHistory = 600
const hist = ref<number[][]>([])

const bands = computed(() => {
  const scaleH = Math.max(0, Math.min(1, (effectiveHeight.value - 120) / 360))
  return Math.max(8, Math.min(32, Math.round(baseBands + scaleH * 8)))
})

watch(
  () => [smoothSamples.value, bands.value],
  () => {
    const samples = smoothSamples.value
    if (!samples.length) return
    const b = bands.value
    const step = Math.max(1, Math.floor(samples.length / b))
    const frame: number[] = new Array(b).fill(0)
    for (let band = 0; band < b; band++) {
      const i0 = band * step
      const i1 = Math.min(samples.length, i0 + step)
      let acc = 0
      let cnt = 0
      for (let i = i0; i < i1; i++) {
        acc += Math.abs(samples[i] || 0)
        cnt++
      }
      const v = cnt ? acc / cnt : 0
      frame[band] = Math.min(1, v * gain.value)
    }
    const next = hist.value.slice()
    const scrollMul = 6
    for (let i = 0; i < scrollMul; i++) next.push(frame)
    if (next.length > maxHistory) {
      hist.value = next.slice(next.length - maxHistory)
    } else {
      hist.value = next
    }
  },
  { deep: true }
)

function heatColor(v: number) {
  const clamp = (x: number) => Math.max(0, Math.min(1, x))
  const enhance = (x: number, c = 1.45, pivot = 0.55) => clamp((x - pivot) * c + pivot)
  const t = enhance(clamp(v))
  const mid = 0.6
  const lerp = (a: number, b: number, t2: number) => Math.round(a + (b - a) * t2)
  if (t <= mid) {
    const u = t / mid
    return `rgb(${lerp(36, 235, u)},${lerp(6, 26, u)},${lerp(13, 80, u)})`
  }
  const u = (t - mid) / (1 - mid)
  return `rgb(${lerp(235, 255, u)},${lerp(26, 214, u)},${lerp(80, 225, u)})`
}

const fsIcon = computed(() => (props.themeName === 'dark' ? fullscreenLight : fullscreenDark))

const trackWidth = computed(() => Math.max(100, effectiveWidth.value - 60))
const fillWidth = computed(() => Math.max(0, Math.min(trackWidth.value, Math.round(rmsSmoothed.value * trackWidth.value))))
</script>

<template>
  <div
    class="viz-panel"
    :style="{ width: `${effectiveWidth}px` }"
    ref="containerRef"
    @mouseenter="hovered = true"
    @mouseleave="hovered = false"
  >
    <div class="viz-stage">
      <svg
        :width="effectiveWidth"
        :height="effectiveHeight"
        :style="{
          background: theme.panelBg ?? theme.panel ?? '#1a0a0f',
          border: '1px solid #1d2a3a',
          borderRadius: '6px'
        }"
        @click="emit('toggle')"
      >
        <WaveViz
          v-if="mode === 'wave'"
          :width="effectiveWidth"
          :height="effectiveHeight"
          :samples="smoothSamples"
          :gain="gain"
          :grid-color="theme.grid"
          :line-color="theme.line ?? theme.accent"
        />
        <BarsViz
          v-else-if="mode === 'bars'"
          :width="effectiveWidth"
          :height="effectiveHeight"
          :samples="smoothSamples"
          :gain="gain"
          :bar-color="theme.line ?? theme.accent"
          :bars="Math.max(32, Math.min(2048, Math.floor((effectiveWidth + gap) / 3)))"
        />
        <WaterfallViz
          v-else
          :width="effectiveWidth"
          :height="effectiveHeight"
          :bands="bands"
          :gap="gap"
          :cell="Math.max(3, Math.min(12, Math.floor(effectiveHeight / bands) - gap))"
          :history="hist"
          :heat-color="heatColor"
          :override-offset-y="0"
        />
      </svg>
      <button
        v-if="!isFullscreen"
        class="fs-btn"
        :style="{
          opacity: hovered ? 1 : 0,
          transform: hovered ? 'translateY(0) scale(1)' : 'translateY(-4px) scale(0.95)'
        }"
        @click.stop="enterFullscreen"
        title="全屏"
      >
        <img :src="fsIcon" alt="fullscreen" width="24" height="24" />
      </button>
    </div>
    <div v-if="!hideRms" class="rms-row" :style="{ width: `${effectiveWidth}px` }">
      <div class="track" :style="{ background: '#3a0b17' }">
        <div class="fill" :style="{ width: `${fillWidth}px`, background: theme.accent }"></div>
      </div>
      <span>RMS {{ Math.round(rmsSmoothed * 100) }}%</span>
    </div>
  </div>
</template>

<style scoped>
.viz-panel {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.viz-stage {
  position: relative;
  width: 100%;
  margin-top: 40px;
}

.fs-btn {
  position: absolute;
  right: 8px;
  top: 8px;
  width: 28px;
  height: 28px;
  border: none;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: opacity 0.18s ease, transform 0.18s ease;
}

.fs-btn img {
  width: 20px;
  height: 20px;
  pointer-events: none;
}

.rms-row {
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 12px;
  color: #6b829e;
  margin-top: -5px;
}

.track {
  flex: 1;
  height: 8px;
  border-radius: 999px;
  overflow: hidden;
}

.fill {
  height: 100%;
  border-radius: 999px;
  transition: width 120ms ease;
}
</style>
